// `.env.json` is generated by the `npm run build` command
import env from './.env.json';

export const environment = {
  production: true,
  api_url: 'http://localhost:3000',
  version: env.npm_package_version,
 
  defaultLanguage: 'tr-TR',
  supportedLanguages: [
    'en-US',
    'tr-TR'
  ]
};
